### ISSUE TITLE
Related Tables

### ISSUE THREAD

**Issue by rockoncali** [cageyjames/GeoJSON-Ballparks#29]
I have a github...hahaha i don't use github. I almost sent you an email for this but decided to put it here. I'm a non-JSON user, so this is more about JSON - are you up for related tables about ballparks? I was thinking about the River Cats here and how a few years back they went from the A's feeder team to the Giant's feeder team, in the spirit of learning about JSON...can that be done? Also, if the answer is yes then maybe i'll do a related table between AAA and Major League teams. :)

**Comment by cageyjames** [comment]
If you can do that, I can get that data in there!

**Comment by cageyjames** [comment]
This was a great idea, I'm combining it with my fix of the stadiums in issue #28.

**Comment by rockoncali** [comment]
I’m off tomorrow, this is on my todo list!
